/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\myProject\\docx\\node_modules\\_@vuepress_core@1.9.7@@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-3f7bc0d2",
    path: "/2020/5/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3f7bc0d2").then(next)
    },
  },
  {
    path: "/2020/5/index.html",
    redirect: "/2020/5/"
  },
  {
    name: "v-0d2622b2",
    path: "/2020/6/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0d2622b2").then(next)
    },
  },
  {
    path: "/2020/6/index.html",
    redirect: "/2020/6/"
  },
  {
    name: "v-39a6fabf",
    path: "/css_docs/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-39a6fabf").then(next)
    },
  },
  {
    path: "/css_docs/index.html",
    redirect: "/css_docs/"
  },
  {
    name: "v-f5d0f542",
    path: "/css_docs/CSS%E5%AA%92%E4%BD%93%E6%9F%A5%E8%AF%A2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f5d0f542").then(next)
    },
  },
  {
    path: "/css_docs/CSS媒体查询.html",
    redirect: "/css_docs/CSS%E5%AA%92%E4%BD%93%E6%9F%A5%E8%AF%A2.html"
  },
  {
    path: "/css_docs/CSS媒体查询.html",
    redirect: "/css_docs/CSS%E5%AA%92%E4%BD%93%E6%9F%A5%E8%AF%A2.html"
  },
  {
    name: "v-46f8877c",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-46f8877c").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-bd943732",
    path: "/css_docs/%E4%B8%80%E4%BA%9Bcss%E7%89%87%E6%AE%B5.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-bd943732").then(next)
    },
  },
  {
    path: "/css_docs/一些css片段.html",
    redirect: "/css_docs/%E4%B8%80%E4%BA%9Bcss%E7%89%87%E6%AE%B5.html"
  },
  {
    path: "/css_docs/一些css片段.html",
    redirect: "/css_docs/%E4%B8%80%E4%BA%9Bcss%E7%89%87%E6%AE%B5.html"
  },
  {
    name: "v-73aeabf1",
    path: "/css_docs/%E4%B8%89%E8%A7%92%E5%BD%A2%E7%9A%84css%E7%94%BB%E6%B3%95.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-73aeabf1").then(next)
    },
  },
  {
    path: "/css_docs/三角形的css画法.html",
    redirect: "/css_docs/%E4%B8%89%E8%A7%92%E5%BD%A2%E7%9A%84css%E7%94%BB%E6%B3%95.html"
  },
  {
    path: "/css_docs/三角形的css画法.html",
    redirect: "/css_docs/%E4%B8%89%E8%A7%92%E5%BD%A2%E7%9A%84css%E7%94%BB%E6%B3%95.html"
  },
  {
    name: "v-cc014bfa",
    path: "/css_docs/%E5%B0%8F%E7%90%83%E6%9D%A5%E5%9B%9E%E6%BB%9A%E5%8A%A8.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-cc014bfa").then(next)
    },
  },
  {
    path: "/css_docs/小球来回滚动.html",
    redirect: "/css_docs/%E5%B0%8F%E7%90%83%E6%9D%A5%E5%9B%9E%E6%BB%9A%E5%8A%A8.html"
  },
  {
    path: "/css_docs/小球来回滚动.html",
    redirect: "/css_docs/%E5%B0%8F%E7%90%83%E6%9D%A5%E5%9B%9E%E6%BB%9A%E5%8A%A8.html"
  },
  {
    name: "v-d4f99c98",
    path: "/css_docs/%E7%BA%AFcss%E5%AE%9E%E7%8E%B0%E4%B8%80%E4%B8%AA%E8%8F%9C%E5%8D%95%E7%9A%84%E9%9A%90%E8%97%8F%E6%98%BE%E7%A4%BA%E5%8A%9F%E8%83%BD.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d4f99c98").then(next)
    },
  },
  {
    path: "/css_docs/纯css实现一个菜单的隐藏显示功能.html",
    redirect: "/css_docs/%E7%BA%AFcss%E5%AE%9E%E7%8E%B0%E4%B8%80%E4%B8%AA%E8%8F%9C%E5%8D%95%E7%9A%84%E9%9A%90%E8%97%8F%E6%98%BE%E7%A4%BA%E5%8A%9F%E8%83%BD.html"
  },
  {
    path: "/css_docs/纯css实现一个菜单的隐藏显示功能.html",
    redirect: "/css_docs/%E7%BA%AFcss%E5%AE%9E%E7%8E%B0%E4%B8%80%E4%B8%AA%E8%8F%9C%E5%8D%95%E7%9A%84%E9%9A%90%E8%97%8F%E6%98%BE%E7%A4%BA%E5%8A%9F%E8%83%BD.html"
  },
  {
    name: "v-32e62000",
    path: "/css_docs/%E9%BC%A0%E6%A0%87%E7%82%B9%E5%87%BB%E6%B0%B4%E6%B3%A2%E6%95%88%E6%9E%9C.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-32e62000").then(next)
    },
  },
  {
    path: "/css_docs/鼠标点击水波效果.html",
    redirect: "/css_docs/%E9%BC%A0%E6%A0%87%E7%82%B9%E5%87%BB%E6%B0%B4%E6%B3%A2%E6%95%88%E6%9E%9C.html"
  },
  {
    path: "/css_docs/鼠标点击水波效果.html",
    redirect: "/css_docs/%E9%BC%A0%E6%A0%87%E7%82%B9%E5%87%BB%E6%B0%B4%E6%B3%A2%E6%95%88%E6%9E%9C.html"
  },
  {
    name: "v-2aefddc7",
    path: "/dart/%E5%85%B6%E4%BB%96.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2aefddc7").then(next)
    },
  },
  {
    path: "/dart/其他.html",
    redirect: "/dart/%E5%85%B6%E4%BB%96.html"
  },
  {
    path: "/dart/其他.html",
    redirect: "/dart/%E5%85%B6%E4%BB%96.html"
  },
  {
    name: "v-4a1a88a2",
    path: "/dart/%E5%87%BD%E6%95%B0.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4a1a88a2").then(next)
    },
  },
  {
    path: "/dart/函数.html",
    redirect: "/dart/%E5%87%BD%E6%95%B0.html"
  },
  {
    path: "/dart/函数.html",
    redirect: "/dart/%E5%87%BD%E6%95%B0.html"
  },
  {
    name: "v-7946293f",
    path: "/dart/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7946293f").then(next)
    },
  },
  {
    path: "/dart/index.html",
    redirect: "/dart/"
  },
  {
    name: "v-37f479e3",
    path: "/dart/%E5%8F%98%E9%87%8F%E5%92%8C%E7%B1%BB%E5%9E%8B.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-37f479e3").then(next)
    },
  },
  {
    path: "/dart/变量和类型.html",
    redirect: "/dart/%E5%8F%98%E9%87%8F%E5%92%8C%E7%B1%BB%E5%9E%8B.html"
  },
  {
    path: "/dart/变量和类型.html",
    redirect: "/dart/%E5%8F%98%E9%87%8F%E5%92%8C%E7%B1%BB%E5%9E%8B.html"
  },
  {
    name: "v-6c4d8ff5",
    path: "/dart/%E7%B1%BB.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6c4d8ff5").then(next)
    },
  },
  {
    path: "/dart/类.html",
    redirect: "/dart/%E7%B1%BB.html"
  },
  {
    path: "/dart/类.html",
    redirect: "/dart/%E7%B1%BB.html"
  },
  {
    name: "v-73fe6a6c",
    path: "/dart/%E8%BF%90%E7%AE%97%E7%AC%A6%E5%92%8C%E6%8E%A7%E5%88%B6%E6%B5%81%E7%A8%8B%E8%AF%AD%E5%8F%A5.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-73fe6a6c").then(next)
    },
  },
  {
    path: "/dart/运算符和控制流程语句.html",
    redirect: "/dart/%E8%BF%90%E7%AE%97%E7%AC%A6%E5%92%8C%E6%8E%A7%E5%88%B6%E6%B5%81%E7%A8%8B%E8%AF%AD%E5%8F%A5.html"
  },
  {
    path: "/dart/运算符和控制流程语句.html",
    redirect: "/dart/%E8%BF%90%E7%AE%97%E7%AC%A6%E5%92%8C%E6%8E%A7%E5%88%B6%E6%B5%81%E7%A8%8B%E8%AF%AD%E5%8F%A5.html"
  },
  {
    name: "v-eaaca09c",
    path: "/js_docs/10%E5%88%86%E9%92%9F%E5%9B%9E%E9%A1%BELocation%E5%AF%B9%E8%B1%A1%E7%9A%84%E5%87%A0%E4%B8%AA%E7%9F%A5%E8%AF%86%E7%82%B9.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-eaaca09c").then(next)
    },
  },
  {
    path: "/js_docs/10分钟回顾Location对象的几个知识点.html",
    redirect: "/js_docs/10%E5%88%86%E9%92%9F%E5%9B%9E%E9%A1%BELocation%E5%AF%B9%E8%B1%A1%E7%9A%84%E5%87%A0%E4%B8%AA%E7%9F%A5%E8%AF%86%E7%82%B9.html"
  },
  {
    path: "/js_docs/10分钟回顾Location对象的几个知识点.html",
    redirect: "/js_docs/10%E5%88%86%E9%92%9F%E5%9B%9E%E9%A1%BELocation%E5%AF%B9%E8%B1%A1%E7%9A%84%E5%87%A0%E4%B8%AA%E7%9F%A5%E8%AF%86%E7%82%B9.html"
  },
  {
    name: "v-1668fe94",
    path: "/js_docs/5%E5%88%86%E9%92%9F%E5%9B%9E%E9%A1%BE%E5%8E%9F%E7%94%9Fajax%E7%9A%84%E5%87%A0%E4%B8%AA%E7%9F%A5%E8%AF%86%E7%82%B9.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1668fe94").then(next)
    },
  },
  {
    path: "/js_docs/5分钟回顾原生ajax的几个知识点.html",
    redirect: "/js_docs/5%E5%88%86%E9%92%9F%E5%9B%9E%E9%A1%BE%E5%8E%9F%E7%94%9Fajax%E7%9A%84%E5%87%A0%E4%B8%AA%E7%9F%A5%E8%AF%86%E7%82%B9.html"
  },
  {
    path: "/js_docs/5分钟回顾原生ajax的几个知识点.html",
    redirect: "/js_docs/5%E5%88%86%E9%92%9F%E5%9B%9E%E9%A1%BE%E5%8E%9F%E7%94%9Fajax%E7%9A%84%E5%87%A0%E4%B8%AA%E7%9F%A5%E8%AF%86%E7%82%B9.html"
  },
  {
    name: "v-bee91c90",
    path: "/js_docs/DOM%E6%93%8D%E4%BD%9C%E5%B8%B8%E7%94%A8API%E6%80%BB%E7%BB%93.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-bee91c90").then(next)
    },
  },
  {
    path: "/js_docs/DOM操作常用API总结.html",
    redirect: "/js_docs/DOM%E6%93%8D%E4%BD%9C%E5%B8%B8%E7%94%A8API%E6%80%BB%E7%BB%93.html"
  },
  {
    path: "/js_docs/DOM操作常用API总结.html",
    redirect: "/js_docs/DOM%E6%93%8D%E4%BD%9C%E5%B8%B8%E7%94%A8API%E6%80%BB%E7%BB%93.html"
  },
  {
    name: "v-dbcb24a2",
    path: "/js_docs/EventTarget%E4%BB%8B%E7%BB%8D.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-dbcb24a2").then(next)
    },
  },
  {
    path: "/js_docs/EventTarget介绍.html",
    redirect: "/js_docs/EventTarget%E4%BB%8B%E7%BB%8D.html"
  },
  {
    path: "/js_docs/EventTarget介绍.html",
    redirect: "/js_docs/EventTarget%E4%BB%8B%E7%BB%8D.html"
  },
  {
    name: "v-15dc4e30",
    path: "/js_docs/JSON%E4%B8%AD%E7%9A%84stringify%E6%96%B9%E6%B3%95.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-15dc4e30").then(next)
    },
  },
  {
    path: "/js_docs/JSON中的stringify方法.html",
    redirect: "/js_docs/JSON%E4%B8%AD%E7%9A%84stringify%E6%96%B9%E6%B3%95.html"
  },
  {
    path: "/js_docs/JSON中的stringify方法.html",
    redirect: "/js_docs/JSON%E4%B8%AD%E7%9A%84stringify%E6%96%B9%E6%B3%95.html"
  },
  {
    name: "v-5a0553f2",
    path: "/js_docs/JS%E7%94%9F%E6%88%90UUID%E7%9A%84%E5%A4%9A%E7%A7%8D%E6%96%B9%E5%BC%8F.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5a0553f2").then(next)
    },
  },
  {
    path: "/js_docs/JS生成UUID的多种方式.html",
    redirect: "/js_docs/JS%E7%94%9F%E6%88%90UUID%E7%9A%84%E5%A4%9A%E7%A7%8D%E6%96%B9%E5%BC%8F.html"
  },
  {
    path: "/js_docs/JS生成UUID的多种方式.html",
    redirect: "/js_docs/JS%E7%94%9F%E6%88%90UUID%E7%9A%84%E5%A4%9A%E7%A7%8D%E6%96%B9%E5%BC%8F.html"
  },
  {
    name: "v-4ebb8fd5",
    path: "/js_docs/JS%E7%B2%BE%E5%BA%A6%E9%97%AE%E9%A2%98.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4ebb8fd5").then(next)
    },
  },
  {
    path: "/js_docs/JS精度问题.html",
    redirect: "/js_docs/JS%E7%B2%BE%E5%BA%A6%E9%97%AE%E9%A2%98.html"
  },
  {
    path: "/js_docs/JS精度问题.html",
    redirect: "/js_docs/JS%E7%B2%BE%E5%BA%A6%E9%97%AE%E9%A2%98.html"
  },
  {
    name: "v-39f79455",
    path: "/js_docs/JS%E8%B0%83%E7%94%A8%E5%87%BD%E6%95%B0%E7%9A%844%E7%A7%8D%E6%96%B9%E5%BC%8F.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-39f79455").then(next)
    },
  },
  {
    path: "/js_docs/JS调用函数的4种方式.html",
    redirect: "/js_docs/JS%E8%B0%83%E7%94%A8%E5%87%BD%E6%95%B0%E7%9A%844%E7%A7%8D%E6%96%B9%E5%BC%8F.html"
  },
  {
    path: "/js_docs/JS调用函数的4种方式.html",
    redirect: "/js_docs/JS%E8%B0%83%E7%94%A8%E5%87%BD%E6%95%B0%E7%9A%844%E7%A7%8D%E6%96%B9%E5%BC%8F.html"
  },
  {
    name: "v-ab9edbb4",
    path: "/js_docs/Map%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ab9edbb4").then(next)
    },
  },
  {
    path: "/js_docs/Map数据结构.html",
    redirect: "/js_docs/Map%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84.html"
  },
  {
    path: "/js_docs/Map数据结构.html",
    redirect: "/js_docs/Map%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84.html"
  },
  {
    name: "v-22df10f4",
    path: "/js_docs/JavaScript%E7%9A%84%E6%89%A7%E8%A1%8C%E6%9C%BA%E5%88%B6.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-22df10f4").then(next)
    },
  },
  {
    path: "/js_docs/JavaScript的执行机制.html",
    redirect: "/js_docs/JavaScript%E7%9A%84%E6%89%A7%E8%A1%8C%E6%9C%BA%E5%88%B6.html"
  },
  {
    path: "/js_docs/JavaScript的执行机制.html",
    redirect: "/js_docs/JavaScript%E7%9A%84%E6%89%A7%E8%A1%8C%E6%9C%BA%E5%88%B6.html"
  },
  {
    name: "v-2b75b0a5",
    path: "/js_docs/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2b75b0a5").then(next)
    },
  },
  {
    path: "/js_docs/index.html",
    redirect: "/js_docs/"
  },
  {
    name: "v-42fa1834",
    path: "/js_docs/Set%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-42fa1834").then(next)
    },
  },
  {
    path: "/js_docs/Set数据结构.html",
    redirect: "/js_docs/Set%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84.html"
  },
  {
    path: "/js_docs/Set数据结构.html",
    redirect: "/js_docs/Set%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84.html"
  },
  {
    name: "v-bd2f6770",
    path: "/js_docs/Storage%E5%AF%B9%E8%B1%A1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-bd2f6770").then(next)
    },
  },
  {
    path: "/js_docs/Storage对象.html",
    redirect: "/js_docs/Storage%E5%AF%B9%E8%B1%A1.html"
  },
  {
    path: "/js_docs/Storage对象.html",
    redirect: "/js_docs/Storage%E5%AF%B9%E8%B1%A1.html"
  },
  {
    name: "v-0088577e",
    path: "/js_docs/instanceof%E5%92%8Ctypeof%E5%8E%9F%E7%90%86%E5%9B%9E%E9%A1%BE.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0088577e").then(next)
    },
  },
  {
    path: "/js_docs/instanceof和typeof原理回顾.html",
    redirect: "/js_docs/instanceof%E5%92%8Ctypeof%E5%8E%9F%E7%90%86%E5%9B%9E%E9%A1%BE.html"
  },
  {
    path: "/js_docs/instanceof和typeof原理回顾.html",
    redirect: "/js_docs/instanceof%E5%92%8Ctypeof%E5%8E%9F%E7%90%86%E5%9B%9E%E9%A1%BE.html"
  },
  {
    name: "v-0f526fe1",
    path: "/js_docs/js%E4%B8%AD%E5%AE%B9%E6%98%93%E5%BF%BD%E7%95%A5%E7%9A%84%E5%8F%82%E6%95%B0.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0f526fe1").then(next)
    },
  },
  {
    path: "/js_docs/js中容易忽略的参数.html",
    redirect: "/js_docs/js%E4%B8%AD%E5%AE%B9%E6%98%93%E5%BF%BD%E7%95%A5%E7%9A%84%E5%8F%82%E6%95%B0.html"
  },
  {
    path: "/js_docs/js中容易忽略的参数.html",
    redirect: "/js_docs/js%E4%B8%AD%E5%AE%B9%E6%98%93%E5%BF%BD%E7%95%A5%E7%9A%84%E5%8F%82%E6%95%B0.html"
  },
  {
    name: "v-186eaaa0",
    path: "/js_docs/new%E7%9A%84%E6%97%B6%E5%80%99%E5%B9%B2%E4%BA%86%E5%95%A5.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-186eaaa0").then(next)
    },
  },
  {
    path: "/js_docs/new的时候干了啥.html",
    redirect: "/js_docs/new%E7%9A%84%E6%97%B6%E5%80%99%E5%B9%B2%E4%BA%86%E5%95%A5.html"
  },
  {
    path: "/js_docs/new的时候干了啥.html",
    redirect: "/js_docs/new%E7%9A%84%E6%97%B6%E5%80%99%E5%B9%B2%E4%BA%86%E5%95%A5.html"
  },
  {
    name: "v-7b01ce36",
    path: "/js_docs/void%200%E4%B8%8Eundefined%E7%9A%84%E5%85%B3%E7%B3%BB.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7b01ce36").then(next)
    },
  },
  {
    path: "/js_docs/void 0与undefined的关系.html",
    redirect: "/js_docs/void%200%E4%B8%8Eundefined%E7%9A%84%E5%85%B3%E7%B3%BB.html"
  },
  {
    path: "/js_docs/void 0与undefined的关系.html",
    redirect: "/js_docs/void%200%E4%B8%8Eundefined%E7%9A%84%E5%85%B3%E7%B3%BB.html"
  },
  {
    name: "v-56996809",
    path: "/js_docs/%E4%B8%80%E6%96%87%E4%BA%86%E8%A7%A3this%E6%8C%87%E5%90%91.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-56996809").then(next)
    },
  },
  {
    path: "/js_docs/一文了解this指向.html",
    redirect: "/js_docs/%E4%B8%80%E6%96%87%E4%BA%86%E8%A7%A3this%E6%8C%87%E5%90%91.html"
  },
  {
    path: "/js_docs/一文了解this指向.html",
    redirect: "/js_docs/%E4%B8%80%E6%96%87%E4%BA%86%E8%A7%A3this%E6%8C%87%E5%90%91.html"
  },
  {
    name: "v-c28922ba",
    path: "/js_docs/with%E8%AF%AD%E6%B3%95.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c28922ba").then(next)
    },
  },
  {
    path: "/js_docs/with语法.html",
    redirect: "/js_docs/with%E8%AF%AD%E6%B3%95.html"
  },
  {
    path: "/js_docs/with语法.html",
    redirect: "/js_docs/with%E8%AF%AD%E6%B3%95.html"
  },
  {
    name: "v-6ef6dd17",
    path: "/js_docs/%E4%B8%80%E7%BD%91%E6%89%93%E5%B0%BDJS%E4%B8%AD%E7%9A%84%E5%BE%AA%E7%8E%AF%E5%92%8C%E9%81%8D%E5%8E%86.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6ef6dd17").then(next)
    },
  },
  {
    path: "/js_docs/一网打尽JS中的循环和遍历.html",
    redirect: "/js_docs/%E4%B8%80%E7%BD%91%E6%89%93%E5%B0%BDJS%E4%B8%AD%E7%9A%84%E5%BE%AA%E7%8E%AF%E5%92%8C%E9%81%8D%E5%8E%86.html"
  },
  {
    path: "/js_docs/一网打尽JS中的循环和遍历.html",
    redirect: "/js_docs/%E4%B8%80%E7%BD%91%E6%89%93%E5%B0%BDJS%E4%B8%AD%E7%9A%84%E5%BE%AA%E7%8E%AF%E5%92%8C%E9%81%8D%E5%8E%86.html"
  },
  {
    name: "v-6980fc10",
    path: "/js_docs/%E5%87%BD%E6%95%B0%E7%9A%84%E5%BD%A2%E5%8F%82%E5%92%8C%E5%AE%9E%E5%8F%82.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6980fc10").then(next)
    },
  },
  {
    path: "/js_docs/函数的形参和实参.html",
    redirect: "/js_docs/%E5%87%BD%E6%95%B0%E7%9A%84%E5%BD%A2%E5%8F%82%E5%92%8C%E5%AE%9E%E5%8F%82.html"
  },
  {
    path: "/js_docs/函数的形参和实参.html",
    redirect: "/js_docs/%E5%87%BD%E6%95%B0%E7%9A%84%E5%BD%A2%E5%8F%82%E5%92%8C%E5%AE%9E%E5%8F%82.html"
  },
  {
    name: "v-578dc8d1",
    path: "/js_docs/%E4%BD%BF%E7%94%A8%E5%8E%9F%E7%94%9Fjs%E5%AE%9E%E7%8E%B0%E4%B8%80%E4%B8%AA%E5%9B%9E%E5%88%B0%E9%A1%B6%E9%83%A8%E7%9A%84%E5%8A%9F%E8%83%BD.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-578dc8d1").then(next)
    },
  },
  {
    path: "/js_docs/使用原生js实现一个回到顶部的功能.html",
    redirect: "/js_docs/%E4%BD%BF%E7%94%A8%E5%8E%9F%E7%94%9Fjs%E5%AE%9E%E7%8E%B0%E4%B8%80%E4%B8%AA%E5%9B%9E%E5%88%B0%E9%A1%B6%E9%83%A8%E7%9A%84%E5%8A%9F%E8%83%BD.html"
  },
  {
    path: "/js_docs/使用原生js实现一个回到顶部的功能.html",
    redirect: "/js_docs/%E4%BD%BF%E7%94%A8%E5%8E%9F%E7%94%9Fjs%E5%AE%9E%E7%8E%B0%E4%B8%80%E4%B8%AA%E5%9B%9E%E5%88%B0%E9%A1%B6%E9%83%A8%E7%9A%84%E5%8A%9F%E8%83%BD.html"
  },
  {
    name: "v-a3a7cd48",
    path: "/js_docs/%E5%87%BD%E6%95%B0%E9%98%B2%E6%8A%96%E5%92%8C%E8%8A%82%E6%B5%81.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a3a7cd48").then(next)
    },
  },
  {
    path: "/js_docs/函数防抖和节流.html",
    redirect: "/js_docs/%E5%87%BD%E6%95%B0%E9%98%B2%E6%8A%96%E5%92%8C%E8%8A%82%E6%B5%81.html"
  },
  {
    path: "/js_docs/函数防抖和节流.html",
    redirect: "/js_docs/%E5%87%BD%E6%95%B0%E9%98%B2%E6%8A%96%E5%92%8C%E8%8A%82%E6%B5%81.html"
  },
  {
    name: "v-0a62d9b5",
    path: "/js_docs/%E5%8E%9F%E5%9E%8B%E5%92%8C%E5%8E%9F%E5%9E%8B%E9%93%BE.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0a62d9b5").then(next)
    },
  },
  {
    path: "/js_docs/原型和原型链.html",
    redirect: "/js_docs/%E5%8E%9F%E5%9E%8B%E5%92%8C%E5%8E%9F%E5%9E%8B%E9%93%BE.html"
  },
  {
    path: "/js_docs/原型和原型链.html",
    redirect: "/js_docs/%E5%8E%9F%E5%9E%8B%E5%92%8C%E5%8E%9F%E5%9E%8B%E9%93%BE.html"
  },
  {
    name: "v-4d1e7dee",
    path: "/js_docs/%E5%A4%9A%E7%A7%8D%E6%96%B9%E5%BC%8F%E5%AE%9E%E7%8E%B0%E5%89%8D%E7%AB%AF%E5%9B%BE%E7%89%87%E4%B8%8B%E8%BD%BD.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4d1e7dee").then(next)
    },
  },
  {
    path: "/js_docs/多种方式实现前端图片下载.html",
    redirect: "/js_docs/%E5%A4%9A%E7%A7%8D%E6%96%B9%E5%BC%8F%E5%AE%9E%E7%8E%B0%E5%89%8D%E7%AB%AF%E5%9B%BE%E7%89%87%E4%B8%8B%E8%BD%BD.html"
  },
  {
    path: "/js_docs/多种方式实现前端图片下载.html",
    redirect: "/js_docs/%E5%A4%9A%E7%A7%8D%E6%96%B9%E5%BC%8F%E5%AE%9E%E7%8E%B0%E5%89%8D%E7%AB%AF%E5%9B%BE%E7%89%87%E4%B8%8B%E8%BD%BD.html"
  },
  {
    name: "v-50217e7a",
    path: "/js_docs/%E5%BF%AB%E6%9D%A5%E5%92%8Cfetch%E7%8E%A9%E8%80%8D%E5%90%A7.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-50217e7a").then(next)
    },
  },
  {
    path: "/js_docs/快来和fetch玩耍吧.html",
    redirect: "/js_docs/%E5%BF%AB%E6%9D%A5%E5%92%8Cfetch%E7%8E%A9%E8%80%8D%E5%90%A7.html"
  },
  {
    path: "/js_docs/快来和fetch玩耍吧.html",
    redirect: "/js_docs/%E5%BF%AB%E6%9D%A5%E5%92%8Cfetch%E7%8E%A9%E8%80%8D%E5%90%A7.html"
  },
  {
    name: "v-498c9d58",
    path: "/js_docs/%E6%B7%B1%E6%8B%B7%E8%B4%9D%E5%92%8C%E6%B5%85%E6%8B%B7%E8%B4%9D%E4%BA%86%E8%A7%A3%E4%B8%80%E4%B8%8B.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-498c9d58").then(next)
    },
  },
  {
    path: "/js_docs/深拷贝和浅拷贝了解一下.html",
    redirect: "/js_docs/%E6%B7%B1%E6%8B%B7%E8%B4%9D%E5%92%8C%E6%B5%85%E6%8B%B7%E8%B4%9D%E4%BA%86%E8%A7%A3%E4%B8%80%E4%B8%8B.html"
  },
  {
    path: "/js_docs/深拷贝和浅拷贝了解一下.html",
    redirect: "/js_docs/%E6%B7%B1%E6%8B%B7%E8%B4%9D%E5%92%8C%E6%B5%85%E6%8B%B7%E8%B4%9D%E4%BA%86%E8%A7%A3%E4%B8%80%E4%B8%8B.html"
  },
  {
    name: "v-379f4445",
    path: "/js_docs/%E6%B5%85%E8%B0%88%E5%9F%BA%E6%9C%AC%E5%8C%85%E8%A3%85%E7%B1%BB%E5%9E%8B.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-379f4445").then(next)
    },
  },
  {
    path: "/js_docs/浅谈基本包装类型.html",
    redirect: "/js_docs/%E6%B5%85%E8%B0%88%E5%9F%BA%E6%9C%AC%E5%8C%85%E8%A3%85%E7%B1%BB%E5%9E%8B.html"
  },
  {
    path: "/js_docs/浅谈基本包装类型.html",
    redirect: "/js_docs/%E6%B5%85%E8%B0%88%E5%9F%BA%E6%9C%AC%E5%8C%85%E8%A3%85%E7%B1%BB%E5%9E%8B.html"
  },
  {
    name: "v-39a74757",
    path: "/node_docs/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-39a74757").then(next)
    },
  },
  {
    path: "/node_docs/index.html",
    redirect: "/node_docs/"
  },
  {
    name: "v-34395401",
    path: "/node_docs/exports%E5%92%8Cmodule.exports.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-34395401").then(next)
    },
  },
  {
    path: "/node_docs/exports和module.exports.html",
    redirect: "/node_docs/exports%E5%92%8Cmodule.exports.html"
  },
  {
    path: "/node_docs/exports和module.exports.html",
    redirect: "/node_docs/exports%E5%92%8Cmodule.exports.html"
  },
  {
    name: "v-a4165618",
    path: "/node_docs/node%E5%8F%91%E9%80%81%E9%82%AE%E4%BB%B6.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a4165618").then(next)
    },
  },
  {
    path: "/node_docs/node发送邮件.html",
    redirect: "/node_docs/node%E5%8F%91%E9%80%81%E9%82%AE%E4%BB%B6.html"
  },
  {
    path: "/node_docs/node发送邮件.html",
    redirect: "/node_docs/node%E5%8F%91%E9%80%81%E9%82%AE%E4%BB%B6.html"
  },
  {
    name: "v-6ba28064",
    path: "/js_docs/%E7%94%9F%E6%88%90%E9%9A%8F%E6%9C%BA%E6%95%B0.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6ba28064").then(next)
    },
  },
  {
    path: "/js_docs/生成随机数.html",
    redirect: "/js_docs/%E7%94%9F%E6%88%90%E9%9A%8F%E6%9C%BA%E6%95%B0.html"
  },
  {
    path: "/js_docs/生成随机数.html",
    redirect: "/js_docs/%E7%94%9F%E6%88%90%E9%9A%8F%E6%9C%BA%E6%95%B0.html"
  },
  {
    name: "v-f2991fd0",
    path: "/other/Flutter%E6%9E%84%E5%BB%BAAndroid%E5%8C%85.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f2991fd0").then(next)
    },
  },
  {
    path: "/other/Flutter构建Android包.html",
    redirect: "/other/Flutter%E6%9E%84%E5%BB%BAAndroid%E5%8C%85.html"
  },
  {
    path: "/other/Flutter构建Android包.html",
    redirect: "/other/Flutter%E6%9E%84%E5%BB%BAAndroid%E5%8C%85.html"
  },
  {
    name: "v-13bfa384",
    path: "/other/Git%E5%B8%B8%E7%94%A8%E6%8C%87%E4%BB%A4.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-13bfa384").then(next)
    },
  },
  {
    path: "/other/Git常用指令.html",
    redirect: "/other/Git%E5%B8%B8%E7%94%A8%E6%8C%87%E4%BB%A4.html"
  },
  {
    path: "/other/Git常用指令.html",
    redirect: "/other/Git%E5%B8%B8%E7%94%A8%E6%8C%87%E4%BB%A4.html"
  },
  {
    name: "v-5fa7754f",
    path: "/other/Markdown%E8%AF%AD%E6%B3%95.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5fa7754f").then(next)
    },
  },
  {
    path: "/other/Markdown语法.html",
    redirect: "/other/Markdown%E8%AF%AD%E6%B3%95.html"
  },
  {
    path: "/other/Markdown语法.html",
    redirect: "/other/Markdown%E8%AF%AD%E6%B3%95.html"
  },
  {
    name: "v-195725e7",
    path: "/other/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-195725e7").then(next)
    },
  },
  {
    path: "/other/index.html",
    redirect: "/other/"
  },
  {
    name: "v-c3f1ce0c",
    path: "/other/npm%E5%8F%91%E5%8C%85%E6%B5%81%E7%A8%8B.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c3f1ce0c").then(next)
    },
  },
  {
    path: "/other/npm发包流程.html",
    redirect: "/other/npm%E5%8F%91%E5%8C%85%E6%B5%81%E7%A8%8B.html"
  },
  {
    path: "/other/npm发包流程.html",
    redirect: "/other/npm%E5%8F%91%E5%8C%85%E6%B5%81%E7%A8%8B.html"
  },
  {
    name: "v-8a7f0fe0",
    path: "/other/tool.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8a7f0fe0").then(next)
    },
  },
  {
    name: "v-cce3a2b8",
    path: "/other/vuepress%E6%90%AD%E5%BB%BA%E4%B8%AA%E4%BA%BA%E5%8D%9A%E5%AE%A2%E5%B9%B6%E9%83%A8%E7%BD%B2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-cce3a2b8").then(next)
    },
  },
  {
    path: "/other/vuepress搭建个人博客并部署.html",
    redirect: "/other/vuepress%E6%90%AD%E5%BB%BA%E4%B8%AA%E4%BA%BA%E5%8D%9A%E5%AE%A2%E5%B9%B6%E9%83%A8%E7%BD%B2.html"
  },
  {
    path: "/other/vuepress搭建个人博客并部署.html",
    redirect: "/other/vuepress%E6%90%AD%E5%BB%BA%E4%B8%AA%E4%BA%BA%E5%8D%9A%E5%AE%A2%E5%B9%B6%E9%83%A8%E7%BD%B2.html"
  },
  {
    name: "v-3e749a5e",
    path: "/other/%E6%9D%A5%E4%BA%86%E8%A7%A3%E4%B8%8B%E5%AD%97%E7%AC%A6%E7%BC%96%E7%A0%81%E7%9A%84%E5%8E%86%E5%8F%B2%E5%90%A7.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3e749a5e").then(next)
    },
  },
  {
    path: "/other/来了解下字符编码的历史吧.html",
    redirect: "/other/%E6%9D%A5%E4%BA%86%E8%A7%A3%E4%B8%8B%E5%AD%97%E7%AC%A6%E7%BC%96%E7%A0%81%E7%9A%84%E5%8E%86%E5%8F%B2%E5%90%A7.html"
  },
  {
    path: "/other/来了解下字符编码的历史吧.html",
    redirect: "/other/%E6%9D%A5%E4%BA%86%E8%A7%A3%E4%B8%8B%E5%AD%97%E7%AC%A6%E7%BC%96%E7%A0%81%E7%9A%84%E5%8E%86%E5%8F%B2%E5%90%A7.html"
  },
  {
    name: "v-29240a17",
    path: "/other/%E5%8F%91%E8%A1%8CERC20%E4%BB%A3%E5%B8%81.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-29240a17").then(next)
    },
  },
  {
    path: "/other/发行ERC20代币.html",
    redirect: "/other/%E5%8F%91%E8%A1%8CERC20%E4%BB%A3%E5%B8%81.html"
  },
  {
    path: "/other/发行ERC20代币.html",
    redirect: "/other/%E5%8F%91%E8%A1%8CERC20%E4%BB%A3%E5%B8%81.html"
  },
  {
    name: "v-585c778a",
    path: "/other/%E7%A7%BB%E5%8A%A8%E7%AB%AF300ms%E5%BB%B6%E8%BF%9F%E4%BB%A5%E5%8F%8A%E7%82%B9%E5%87%BB%E7%A9%BF%E9%80%8F.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-585c778a").then(next)
    },
  },
  {
    path: "/other/移动端300ms延迟以及点击穿透.html",
    redirect: "/other/%E7%A7%BB%E5%8A%A8%E7%AB%AF300ms%E5%BB%B6%E8%BF%9F%E4%BB%A5%E5%8F%8A%E7%82%B9%E5%87%BB%E7%A9%BF%E9%80%8F.html"
  },
  {
    path: "/other/移动端300ms延迟以及点击穿透.html",
    redirect: "/other/%E7%A7%BB%E5%8A%A8%E7%AB%AF300ms%E5%BB%B6%E8%BF%9F%E4%BB%A5%E5%8F%8A%E7%82%B9%E5%87%BB%E7%A9%BF%E9%80%8F.html"
  },
  {
    name: "v-3422df30",
    path: "/other/%E7%AE%80%E7%AE%80%E5%8D%95%E5%8D%95%E7%9A%84%E6%9D%A5%E5%85%A5%E4%B8%AAdeno%E7%9A%84%E9%97%A8%E5%90%A7.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3422df30").then(next)
    },
  },
  {
    path: "/other/简简单单的来入个deno的门吧.html",
    redirect: "/other/%E7%AE%80%E7%AE%80%E5%8D%95%E5%8D%95%E7%9A%84%E6%9D%A5%E5%85%A5%E4%B8%AAdeno%E7%9A%84%E9%97%A8%E5%90%A7.html"
  },
  {
    path: "/other/简简单单的来入个deno的门吧.html",
    redirect: "/other/%E7%AE%80%E7%AE%80%E5%8D%95%E5%8D%95%E7%9A%84%E6%9D%A5%E5%85%A5%E4%B8%AAdeno%E7%9A%84%E9%97%A8%E5%90%A7.html"
  },
  {
    name: "v-3a310a7f",
    path: "/plan/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3a310a7f").then(next)
    },
  },
  {
    path: "/plan/index.html",
    redirect: "/plan/"
  },
  {
    name: "v-19277298",
    path: "/plan/200525-200531.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-19277298").then(next)
    },
  },
  {
    name: "v-db3cdd02",
    path: "/react_docs/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-db3cdd02").then(next)
    },
  },
  {
    path: "/react_docs/index.html",
    redirect: "/react_docs/"
  },
  {
    name: "v-1fe37312",
    path: "/vue_docs/%E6%95%B0%E6%8D%AE%E5%93%8D%E5%BA%94%E5%BC%8F.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1fe37312").then(next)
    },
  },
  {
    path: "/vue_docs/数据响应式.html",
    redirect: "/vue_docs/%E6%95%B0%E6%8D%AE%E5%93%8D%E5%BA%94%E5%BC%8F.html"
  },
  {
    path: "/vue_docs/数据响应式.html",
    redirect: "/vue_docs/%E6%95%B0%E6%8D%AE%E5%93%8D%E5%BA%94%E5%BC%8F.html"
  },
  {
    name: "v-5e2975df",
    path: "/vue_docs/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5e2975df").then(next)
    },
  },
  {
    path: "/vue_docs/index.html",
    redirect: "/vue_docs/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]